# Project information
site_name: FEXL Guide
site_description: Fighting EX Layer resources and guides
site_author: FEXL Discord
site_url: https://fexl.netlify.com

# Change this to your discord invite link
repo_name: Join the FEXL Discord
repo_url: https://discord.gg/Jxs6448
edit_uri: ""

theme:
  name: 'material'
  custom_dir: 'theme'
  palette:
    primary: 'Amber'
    accent: 'Amber'

extra_css:
  - stylesheets/dark_theme.css
  - stylesheets/codehilite.css

extra:
  social:
    - type: discord
      link: https://discord.gg/Jxs6448

markdown_extensions:
  - admonition
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols:
      fractions: false
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

nav:
  - Home: 'index.md'
  - Systems:
    - Mechanics: 'system/system-mechanics.md'
    - Gougi: 'system/gougi.md'
  - Characters:
    - Allen Snider: 'characters/allen-snider.md'
    - Area: 'characters/area.md'
    - Blair Dame: 'characters/blair-dame.md'
    - Darun Mister: 'characters/darun-mister.md'
    - Doctrine Dark: 'characters/doctrine-dark.md'
    - Garuda: 'characters/garuda.md'
    - Hayate: 'characters/hayate.md'
    - Hokuto: 'characters/hokuto.md'
    - Jack: 'characters/jack.md'
    - Kairi: 'characters/kairi.md'
    - Pullum Purna: 'characters/pullum-purna.md'
    - Sanane: 'characters/sanane.md'
    - Shadow Geist: 'characters/shadow-geist.md'
    - Sharon: 'characters/sharon.md'
    - Shirase: 'characters/shirase.md'
    - Skullomania: 'characters/skullomania.md'
    - Terry Bogard: 'characters/terry-bogard.md'
    - Vulcano Rosso: 'characters/vulcano-rosso.md'